[application]

# dioxus project name
name = "recipe-web"

# default platfrom
# you can also use `dioxus serve/build --platform XXX` to use other platform
# value: web | desktop
default_platform = "web"

# Web `build` & `serve` dist path
out_dir = "dist"

# resource (static) file folder
asset_dir = "public"

[web.app]

# HTML title tag content
title = "Recipe Planner"

index_on_404 = true

[[web.proxy]]

# URL to which requests will be proxied.
# Requests to the /graphql path will be proxied to the backend.
backend = "http://localhost:8000/graphql"

[web.watcher]

watch_path = ["src", "../recipe-app"]

# include `assets` in web platform
[web.resource]

# CSS style file
style = []

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[application.plugins]

available = true

required = []
