[package]
name = "recipe-shuttle"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
recipe-server.workspace = true
shuttle-axum = "0.34.1"
shuttle-runtime = "0.34.1"
