[package]
name = "recipe-shuttle"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-trait = "0.1.60"
axum = "0.6.1"
recipe-db.workspace = true
recipe-graphql.workspace = true
recipe-server = { workspace = true, features = ["embed"] }
serde = { workspace = true, features = ["derive"] }
shuttle-axum = "0.21.0"
shuttle-common = "0.21.0"
shuttle-runtime = "0.21.0"
shuttle-service = "0.21.0"
tokio.workspace = true
