[package]
name = "recipe-shuttle"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-trait = "0.1.60"
axum = "0.6.1"
# recipe-db = { workspace = true }
# recipe-graphql = { workspace = true }
# recipe-server = { workspace = true }
# Shuttle doesn't work with path dependencies so we need to push all these to git before deploying.
recipe-db = { git = "https://github.com/sd2k/recipes", rev = "0ff3e2665e69fb3f4e5048d71ea73b65f16c9d58" }
recipe-graphql = { git = "https://github.com/sd2k/recipes", rev = "0ff3e2665e69fb3f4e5048d71ea73b65f16c9d58" }
recipe-server = { git = "https://github.com/sd2k/recipes", rev = "0ff3e2665e69fb3f4e5048d71ea73b65f16c9d58", features = ["embed"] }
shuttle-service = { version = "0.8.0", features = ["web-axum"] }
sync_wrapper = "0.1.1"

[patch.crates-io]
axum-macros = { git = "https://github.com/sd2k/axum", branch = "remove-rust-toolchain" }
