[workspace]
members = [
  "crates/*"
]

[workspace.dependencies]
anyhow = "1.0.68"
async-graphql = "5.0.4"
async-graphql-axum = "5.0.4"
axum = "0.6.1"
bigdecimal = "0.3.0"
chrono = "0.4.23"
diesel = "2.0.2"
diesel-async = "0.2.0"
futures-util = "0.3.25"
serde = "1.0.152"
thiserror = "1.0.38"
tokio = "1.23.0"
tracing = "0.1.37"
